name: ummah_chat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  easy_localization: ^3.0.7   # or latest version

  supabase_flutter: ^2.10.3
  provider: ^6.0.5
  image_picker: ^1.1.0
  video_player: ^2.10.1
  video_thumbnail: ^0.5.3
  video_compress: ^3.1.2
  image_cropper: ^11.0.0

  # Voice recording
  flutter_sound: ^9.2.13
  permission_handler: ^11.0.0

  # Voice playback
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  just_audio_background: ^0.0.1-beta.11
  visibility_detector: ^0.4.0+2

  uuid: ^4.5.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0

  firebase_core: ^3.7.0
  firebase_messaging: ^15.0.0

  wechat_assets_picker: ^10.0.0
  photo_manager: ^3.8.3
  photo_manager_image_provider: ^2.0.0

  http: ^1.2.2
  share_plus: ^10.0.0
  async: ^2.11.0
  image: ^4.2.0






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/ummah_chat_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_page_image_green.png
    - assets/images/onboarding_ummah_chat_1.png
    - assets/images/onboarding_dua_wall.png
    - assets/images/onboarding_stories_communities.png
    - assets/images/man_normal_hair.png
    - assets/images/man_hair_beard.png
    - assets/images/man_beard_headwear.png
    - assets/images/woman_loose_hair.png
    - assets/images/woman_hijab.png
    - assets/images/woman_niqab.png
    # ðŸ”‘ Add this when you create the translation files:
    - assets/lang/
